#! /bin/bash
set -e
MACPORTS_VERSION=2.8.1
MACOS_VERSION=$(sw_vers -productVersion)
case $MACOS_VERSION in
	14.*)
		MACOS_NAME=14-Sonoma
        ;;
	13.*)
		MACOS_NAME=13-Ventura
		;;
    12.*)
        MACOS_NAME=12-Monterey
        ;;
    11.*)
        MACOS_NAME=11-BigSur
        ;;
    10.15.*)
        MACOS_NAME=10.15-Catalina
        ;;
    10.14.*)
        MACOS_NAME=10.14-Mojave
        ;;
    *)
        error "Unknown MacOS Version"
esac

INSTALLER_NAME=MacPorts-${MACPORTS_VERSION}-${MACOS_NAME}.pkg

log "Download $INSTALLER_NAME"
curl -o "${PROJECT_DIR}/tmp/${INSTALLER_NAME}" -L "https://github.com/macports/macports-base/releases/download/v${MACPORTS_VERSION}/${INSTALLER_NAME}"

log "Install xcode tools"
xcode-select --install || true

log "Run macports installer"
sudo installer -pkg "${PROJECT_DIR}/tmp/${INSTALLER_NAME}" -target /
