#! /bin/bash

VERSION=3.7.3
FILENAME=Nextcloud-$VERSION.pkg
curl -L -o "$TMP_DIR/$FILENAME" "https://github.com/nextcloud/desktop/releases/download/v${VERSION}/$FILENAME"
sudo installer -pkg "$TMP_DIR/$FILENAME" -target /