#!/bin/bash

##############################################################
### Customizations start here ################################
##############################################################

# Barebones cookbook that accepts args to run single recipes

# Get current directory for future use in links
cd $(dirname $0)
PROJECT_DIR=$(pwd)

# Initialization - DO NOT REMOVE
. helpers/initialize

detect_package_manager

init_paths_and_vars

# Get params
COOKBOOK_NAME=$1
RECIPIE=$2
# SET_INSTALLED=$3

recipe $RECIPIE
# set_installed $SET_INSTALLED
