#!/bin/bash

##############################################################
### Customizations start here ################################
##############################################################

# Barebones cookbook that accepts args to run single recipes

# Get current directory for future use in links
cd "$(dirname "$0")" || { echo "Could not change directory to $0"; exit 1;}
PROJECT_DIR=$(pwd)
export PROJECT_DIR

# Initialization - DO NOT REMOVE
. helpers/initialize

detect_package_manager

init_paths_and_vars

# Get params
export COOKBOOK_NAME=$1
RECIPIE=$2
# SET_INSTALLED=$3

recipe "$RECIPIE"
# set_installed $SET_INSTALLED
