#!/bin/bash

# Get current directory for future use in links
cd "$(dirname "$0")" || { echo "Could not change directory to $0"; exit 1;}
PROJECT_DIR=$(pwd)
export PROJECT_DIR

# Initialization - DO NOT REMOVE
. "$PROJECT_DIR/helpers/initialize"

##############################################################
### Customizations start here ################################
##############################################################

init_paths_and_vars

### Run recipes
recipe 'packages'
recipe 'dotfiles'
recipe 'bin'
recipe 'git'
recipe 'vim-settings'

if command_exist 'fish' || is_installed 'build-fish' ; then
    recipe 'fish'
fi

### Show the Finished banner
finished

# vim: set tabstop=2:softtabstop=2:shiftwidth=2:expandtab
