#!/bin/bash

# Initialization - DO NOT REMOVE
. helpers/initialize

##############################################################
### Customizations start here ################################
##############################################################

# Get current directory for future use in links
cd "$(dirname "$0")" || { echo "Could not change directory to $0"; exit 1;}
PROJECT_DIR=$(pwd)
export PROJECT_DIR

init_paths_and_vars

# Require human intervention, do first and get out of the way
install "bitwarden"
install "yubico_auth"
install "nextcloud"
install "macports"

# Automated
install "generate_ssh_keys"
install "finicky"
install "firefox"
install "bettertouchtool"
install "textmate"
install "dash"
