#!/bin/bash

# Initialization - DO NOT REMOVE
. helpers/initialize

##############################################################
### Customizations start here ################################
##############################################################

# Get current directory for future use in links
cd "$(dirname "$0")" || { echo "Could not change directory to $0"; exit 1;}
PROJECT_DIR=$(pwd)
export PROJECT_DIR

init_paths_and_vars

function install() {
    if ! is_installed "$1" ; then
        recipe "$1"
        set_installed "$1"
    fi
}

install "macports"
install "finicky"
install "bitwarden"
install "nextcloud"
install "bettertouchtool"
