#!/bin/bash

# Initialization - DO NOT REMOVE
. helpers/initialize

##############################################################
### Customizations start here ################################
##############################################################

# Get current directory for future use in links
cd $(dirname $0)
PROJECT_DIR=$(pwd)

detect_package_manager

init_paths_and_vars

# Do prompting early to make longer install easier
install_packages=false
if ! is_installed "packages" || prompt_yn "Reinstall packages?" ; then
    install_packages=true
fi

build_vim=false
if [ "$PACKAGE_MANAGER" == 'apt-get' ]; then
    # Optional
    is_installed "build-vim"
    if prompt_yn "Compile vim?" ; then
        build_vim=true
    fi
fi

build_neovim=false
if ! command_exist 'nvim' && prompt_yn "Build Neovim?" ; then
    build_neovim=true
fi

build_fish=false
if ! command_exist 'fish' && prompt_yn "Build Fish?" ; then
    build_fish=true
fi

# Optional
install_sfdc=false
is_installed "salesforce"
if prompt_yn "Install Salesforce tools?" ; then
    install_sfdc=true
fi

# Optional
install_golang=false
is_installed "golang"
if prompt_yn "Install Go?" ; then
    install_golang=true
fi

### Run recipes
if $install_packages ; then
    recipe 'packages'
    set_installed "packages"
fi

recipe 'dotfiles'
recipe 'bin'
recipe 'git'
recipe 'vim-settings'
recipe 'fish'

git submodule init
git submodule update

if $build_vim ; then
    recipe 'build-vim'
    set_installed "build-vim"
fi

if $build_neovim ; then
    recipe 'build-neovim'
    set_installed "neovim"
fi

if $build_fish ; then
    recipe 'build-fish'
    set_installed "build-fish"
fi

if $install_sfdc ; then
    recipe 'salesforce'
    set_installed 'salesforce'
fi

if $install_golang ; then
    recipe 'golang'
    set_installed 'golang'
fi

### Show the Finished banner
finished

# vim: set tabstop=2:softtabstop=2:shiftwidth=2:expandtab
