#!/bin/bash

# Initialization - DO NOT REMOVE
. helpers/initialize

##############################################################
### Customizations start here ################################
##############################################################

# Get current directory for future use in links
cd "$(dirname "$0")" || { echo "Could not change directory to $0"; exit 1;}
PROJECT_DIR=$(pwd)
export PROJECT_DIR

detect_package_manager

init_paths_and_vars

# Do prompting early to make longer install easier
install_packages=false
if ! is_installed "packages" || prompt_yn "Reinstall packages?" ; then
    install_packages=true
fi

# Run recipes
if $install_packages ; then
    recipe 'packages'
    set_installed "packages"
fi

recipe 'dotfiles'
recipe 'bin'
if [ "$(uname)" == 'Darwin' ]; then
    recipe 'mac-files'
    recipe 'mac-bin'
fi
recipe 'git'
recipe 'vim-settings'
recipe 'fish'

git submodule init
git submodule update

### Show the Finished banner
finished

# vim: set tabstop=2:softtabstop=2:shiftwidth=2:expandtab
