#!/bin/bash

# Initialization - DO NOT REMOVE
. helpers/initialize

##############################################################
### Customizations start here ################################
##############################################################

# Get current directory for future use in links
cd $(dirname $0)
PROJECT_DIR=$(pwd)

install_vim_src=false
if [ "$PACKAGE_MANAGER" == 'apt-get' ]; then
    is_installed "vim-from-source"
    if prompt_yn "Compile vim?" ; then
        install_vim_src=true
    fi
fi
install_vim_settings=false
if ! is_installed "vim-settings" || prompt_yn "Reinstall vim-settings?" ; then
    install_vim_settings=true
fi
install_sfdc=false
is_installed "salesforce"
if prompt_yn "Install Salesforce tools?" ; then
    install_sfdc=true
fi

# Create workspace dir
mkdir -p ~/workspace

### Run recipes
recipe 'dotfiles'
recipe 'bin'
recipe 'git'

if $install_vim_src ; then
    recipe 'compile-install-vim'
    set_installed "vim-from-source"
fi

if $install_vim_settings ; then
    recipe 'vim-settings'
    set_installed 'vim-settings'
fi

if $install_sfdc ; then
    recipe 'salesforce'
    set_installed 'salesforce'
fi

### Show the Finished banner
finished

# vim: set tabstop=2:softtabstop=2:shiftwidth=2:expandtab
