#!/bin/bash

# Initialization - DO NOT REMOVE
. helpers/initialize

##############################################################
### Customizations start here ################################
##############################################################

# Get current directory for future use in links
cd $(dirname $0)
PROJECT_DIR=$(pwd)

init_paths_and_vars

install_vim_src=false
is_installed "vim-from-source"
if prompt_yn "Compile vim?" ; then
    install_vim_src=true
fi
install_vim_settings=false
if ! is_installed "vim-settings" || prompt_yn "Reinstall vim-settings?" ; then
    install_vim_settings=true
fi
install_sfdc=false
is_installed "salesforce"
if prompt_yn "Install Salesforce tools?" ; then
    install_sfdc=true
fi
install_fish=false
install_ohmyfish=false
install_fisherman=false
is_installed "fish"
is_installed "oh-my-fish"
is_installed "fisherman"
if prompt_yn "Install fish?" ; then
    install_fish=true

    if prompt_yn "Install oh-my-fish?" ; then
        install_ohmyfish=true
    elif prompt_yn "Install Fisherman?" ; then
        install_fisherman=true
    fi
fi

### Run recipes
recipe 'dotfiles'
recipe 'bin'
recipe 'git'

if $install_vim_src ; then
    recipe 'compile-install-vim'
    set_installed "vim-from-source"
fi

if $install_vim_settings ; then
    recipe 'vim-settings'
    set_installed 'vim-settings'
fi

if $install_sfdc ; then
    recipe 'salesforce'
    set_installed 'salesforce'
fi

if $install_fish ; then
    if ! command_exist fish ; then
        recipe 'fish-install'
    fi
    if command_exist fish ; then
        set_installed 'fish'
    fi
fi

if $install_ohmyfish ; then
    recipe 'oh-my-fish'
    set_installed 'oh-my-fish'
fi

if $install_fisherman ; then
    recipe 'fisherman'
    set_installed 'fisherman'
fi

### Show the Finished banner
finished

# vim: set tabstop=2:softtabstop=2:shiftwidth=2:expandtab
