#!/bin/bash

# Initialization - DO NOT REMOVE
. helpers/initialize

##############################################################
### Customizations start here ################################
##############################################################

# Get current directory for future use in links

cd $(dirname $0)
PROJECT_DIR=$(pwd)

WORKSPACE=$HOME/workspace
mkdir -p $WORKSPACE

if prompt_yn "Install Salesforce tools?" ; then
    recipe 'salesforce'
fi

### Show the Finished banner
finished

# vim: set tabstop=2:softtabstop=2:shiftwidth=2:expandtab
