#! /bin/bash

# Link files that can't be sourced
try_link "ackrc" "$HOME/.ackrc"
try_link "antrc" "$HOME/.antrc"
try_link "ctags" "$XDG_CONFIG_HOME/ctags"
try_link "tig" "$XDG_CONFIG_HOME/tig"
try_link "npmrc" "$HOME/.npmrc"
try_link "tmux" "$XDG_CONFIG_HOME/tmux"

# Source files that can
source_dotfile "bashrc"
source_dotfile "bash_profile"
source_dotfile "bash_alias"
source_dotfile "bash_funcs"
source_dotfile "zshrc"
