#! /bin/bash

# Install fisherman
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher

# Link fisher configs
rm -fr "$XDG_CONFIG_HOME/fisherman"
try_link "${DEFAULT_ASSETS_PATH}/fisherman" "$XDG_CONFIG_HOME/fisherman"

# Install from fishfile
fish -c 'fisher; exit'
