#! /bin/bash

sudo_package 'fish'

if [ ! -d $HOME/.oh-my-fish ]; then
    curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | fish
fi

OMF_CUSTOM=$DEFAULT_ASSETS_PATH/custom
FISH_CONFIG=$HOME/.config/fish/config.fish

if [ ! -f $FISH_CONFIG ]; then
    touch $FISH_CONFIG
fi

add_line 'set fish_path $HOME/.oh-my-fish' $FISH_CONFIG
add_line "set fish_custom $OMF_CUSTOM" $FISH_CONFIG
add_line '. $fish_path/oh-my-fish.fish' $FISH_CONFIG
