#! /bin/bash

# Link and add source all synced fish configs

mkdir -p "$XDG_CONFIG_HOME/fish"
touch "$XDG_CONFIG_HOME/fish/config.fish"

try_link "$DEFAULT_ASSETS_PATH" "$XDG_CONFIG_HOME/fish/synced"
add_line "set -gx fish_synced_dir $XDG_CONFIG_HOME/fish/synced" "$XDG_CONFIG_HOME/fish/config.fish"
add_line "source $XDG_CONFIG_HOME/fish/synced/init.fish" "$XDG_CONFIG_HOME/fish/config.fish"
