#! /bin/bash

local omf_config="$XDG_CONFIG_HOME/omf"
try_link "$DEFAULT_ASSETS_PATH" "$omf_config"

if [ ! -d "$XDG_DATA_HOME/.omf" ]; then
    curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
fi
