#! /bin/bash

# Set some Git Config options
# Set vim as default git editor
git config --global core.editor "vim"
# Turn on colors
git config --global color.ui auto
# Set diff tool to vimdiff
git config --global diff.tool vimdiff
# Suppress launching prompt
git config --global difftool.prompt false
# Create global ignore file
mkdir -p "$XDG_CONFIG_HOME/git/"
git config --global core.excludesfile "$XDG_CONFIG_HOME/git/exclude_global"
try_link "exclude_global" "$XDG_CONFIG_HOME/git/exclude_global"
