#!/bin/bash

# Installs golang from the web

version="1.13.3"
if [[ "$UNAME_STR" == "Darwin" ]]; then
    wget -P "$TMP_DIR/" "http://golang.org/dl/go${version}.darwin-amd64-osx10.8.pkg"
    installer -pkg "$TMP_DIR/go${version}.darwin-amd64-osx10.8.pkg"
elif [[ "$UNAME_STR" == "Linux" ]]; then
    wget -P "$TMP_DIR/" "http://golang.org/dl/go${version}.linux-amd64.tar.gz"
    # Do something
    echo "**** Install from $TMP_DIR/go${version}.linux-amd64.tar.gz"
fi
