#! /bin/bash

sudo_package_update
sudo_package 'tmux htop curl wget mercurial ctags tig pv jq fish mosh bash-completion doxygen'

# This now installs a lot of language specific stuff from python, gradle, and go, to rust.
# Should consider pulling these into different recipes that are dependent on the environment
# that I wish to bootstrap. If not a dev environment, I can trim out some of this.

# Manager specific packages
case "$PACKAGE_MANAGER" in
    "port")
        # Non-standard packages
        sudo_package 'the_silver_searcher md5sha1sum gradle go bash apache-ant'
        # Rust
        sudo_package'rust cargo'
        # Python packages
        sudo_package 'python27 py27-ipython py27-pip py27-six py27-tox py27-flake8 py27-virtualenv'
        sudo_package 'python37 py37-ipython py37-pip py37-six py37-tox py37-flake8 py37-virtualenv'
        sudo port select --set python python27
        sudo port select --set python2 python27
        sudo port select --set python3 python37
        sudo port select --set ipython py27-ipython
        sudo port select --set ipython2 py27-ipython
        sudo port select --set ipython3 py37-ipython
        sudo port select --set pip pip27
        sudo port select --set tox tox27
        sudo port select --set flake8 flake8-27
        sudo port select --set virtualenv virtualenv27
        # Macvim with ruby and python support
        # sudo_package 'macvim +ruby +python27'
        # Vim with ruby and python support
        sudo_package 'vim +ruby +python27'
        # Newer version of git with completion
        sudo_package 'git +bash_completion'
        # Neovim with python plugins
        sudo_package 'neovim py-neovim py27-neovim py37-neovim'
        ;;
    "apt-get")
        if [ -n "$(apt-cache policy silversearcher-ag)" ] ; then
            sudo_package 'silversearcher-ag'
        fi
        sudo_package 'build-essential vim golang-go'
        # Rust
        sudo_package 'rustc cargo'
        ;;
esac
