#! /bin/bash

sudo_package_update
sudo_package 'tmux htop curl wget mercurial ctags tig pv jq fish mosh bash-completion'

# Manager specific packages
case "$PACKAGE_MANAGER" in
    "port")
        sudo_package 'the_silver_searcher doxygen md5sha1sum gradle go bash apache-ant'
        # sudo_package 'macvim +ruby +python27'
        sudo_package 'vim +ruby +python27'
        sudo_package 'git-core +bash_completion'
        ;;
    "apt-get")
        if [ -n "$(apt-cache policy silversearcher-ag)" ] ; then
            sudo_package 'silversearcher-ag'
        fi
        sudo_package 'build-essential vim'
        ;;
esac

# Install ruby gems
# TODO: Install RVM and other ruby requirements and get ruby 1.9.2
sudo gem install rake

# install python packages
sudo pip install -U pip ipython flake8 virtualenv
