#! /bin/bash

# TODO: Prompt for atf or force

install_atf=false
if prompt_yn "Install Abuse the Force?" ; then
    install_atf=true
fi

install_fcli=false
if prompt_yn "Install Force Cli?" ; then
    install_fcli=true
fi

if $install_atf ; then
    recipe 'abuse-the-force'
fi

if $install_fcli ; then
    recipe 'force-cli'
fi

for f in $DEFAULT_ASSETS_PATH/* ; do
    try_link "$f" "$USER_BIN/$(basename $f)"
done

