#! /bin/bash
VIM_SETTINGS_DIR=$WORKSPACE/vim-settings

# Clone vundle if not done already
if [ ! -d $VIM_SETTINGS_DIR ]; then
    log "Cloning vim-settings"
    git clone https://github.com/ViViDboarder/vim-settings $VIM_SETTINGS_DIR
    (cd $VIM_SETTINGS_DIR && ./vim-sync-append.sh)
else
    log "Updating vim-settings"
    (cd $VIM_SETTINGS_DIR && git pull)
fi
