#! /bin/bash
vim_settings_dir="$WORKSPACE/vim-settings"

# Clone vundle if not done already
if [ ! -d "$vim_settings_dir" ]; then
    log "Cloning vim-settings"
    git clone https://github.com/ViViDboarder/vim-settings "$vim_settings_dir"
    (cd "$vim_settings_dir" && ./vim-sync-append.sh)
else
    log "Updating vim-settings"
    (cd "$vim_settings_dir" && git pull)
fi
