#! /bin/bash

log "Compiling and installing fish-shell to local prefix"

function main() {
    local fish_shell_dir=$WORKSPACE/fish-shell

    if [ ! -d "$fish_shell_dir" ]; then
        log "Cloning fish-shell"
        git clone https://github.com/fish-shell/fish-shell "$fish_shell_dir"
    else
        (cd "$fish_shell_dir" && git pull)
    fi

    (cd "$fish_shell_dir" && ./configure --prefix="$LOCAL_PREFIX" --disable-shared && make && make install)
}

main
